apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-04-11T21:27:00Z"
  labels:
    app: it-tools
  name: it-tools
  namespace: default
  resourceVersion: "10447"
  uid: 9d9c3d5a-d3e0-4eba-8bcb-3b49a3fd1989
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.20.245
  clusterIPs:
  - 10.106.20.245
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30513
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: it-tools
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.106.20.245
      ipMode: VIP
