apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-04-10T19:03:38Z"
  generation: 1
  labels:
    app: it-tools
  name: it-tools
  namespace: default
  resourceVersion: "340468"
  uid: 9407ea15-63a9-4cba-bf29-da355bf12644
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: it-tools
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: it-tools
    spec:
      containers:
      - image: corentinth/it-tools:latest
        imagePullPolicy: Always
        name: it-tools
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-10T19:03:38Z"
    lastUpdateTime: "2025-04-10T19:03:43Z"
    message: ReplicaSet "it-tools-6f9bd54c48" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-11T19:01:12Z"
    lastUpdateTime: "2025-04-11T19:01:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
