apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-04-11T21:25:25Z"
  generation: 1
  labels:
    app: it-tools
  name: it-tools
  namespace: default
  resourceVersion: "10366"
  uid: d6216467-a995-4c30-882b-29d9f64154e9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: it-tools
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: it-tools
    spec:
      containers:
      - image: corentinth/it-tools:latest
        imagePullPolicy: Always
        name: it-tools
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-11T21:25:27Z"
    lastUpdateTime: "2025-04-11T21:25:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-11T21:25:25Z"
    lastUpdateTime: "2025-04-11T21:25:27Z"
    message: ReplicaSet "it-tools-6f9bd54c48" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
