apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-busybox-pod
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: busybox-pod
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {} # Allows all ingress traffic
  egress:
    - {} # Allows all egress traffic
