apiVersion: v1
kind: Service
metadata:
  name: busybox
  namespace: default
  author: thomas_rausch
  labels:
    app: busybox
spec:
  selector:
    app: busybox
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: ClusterIP
