# https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-tools
spec:
  defaultBackend:
    service:
      name: it-tools
      port:
        number: 80
