apiVersion: v1
kind: Pod
metadata:
  name: pod-allow-priv-escalation
  namespace: restricted-ns
spec:
  containers:
  - name: container-allow-priv-escalation
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      allowPrivilegeEscalation: true
