# https://blog.devgenius.io/5-secret-kubernetes-tricks-you-didnt-know-6d930dfdfffa
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: default-env-vars
spec:
  selector:
    matchLabels:
      env: production
  env:
  - name: LOG_LEVEL
    value: info
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
