apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2025-07-22T13:53:53Z"
  name: pvviewer
  namespace: default
  resourceVersion: "4132810"
  uid: c986f2dc-e267-4206-9e35-1c9672654c20
