apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-whisker
  labels:
    projectcalico.org/name: ingress-nginx
spec:
  rules:
  - host: 192.136.0.136
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whisker
            port:
              number: 8081
  ingressClassName: nginx
