apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whisker-ingress
  namespace: calico-system 
  labels:
    projectcalico.org/name: ingress-nginx
    k8s-app: whisker
spec:
  rules:
  - host: master-node
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whisker
            port:
              number: 8081
  ingressClassName: nginx
