# Purpose : Form Kubernetes Gateway Object
# Required Kubernetes API Resource
#   NAME             SHORTNAMES  APIVERSION                     NAMESPACED   KIND
#   gateways         gtw         gateway.networking.k8s.io/v1   true         Gateway
#
apiVersion: gateway.networking.k8s.io/v1       # Set API resource
kind: Gateway                                  # Set object kind
metadata:
  name: listen-tcp-3306-allow-tcproute-mysql   # Set object name
  namespace: mysql                             # Object is in effect in Namespace "mysql"     
  annotations:
    creator/author: "Thomas Rausch, Atos"      # Set creator/author
    version: "2025-12-03"                      # Set version
    description: "Form Gateway object of GatewayClass 'tigera-gateway-class' listening on TCP Port 3306 allow only TCPRoute"  # Set description
    reference: "https://docs.tigera.io/calico/latest/networking/ingress-gateway/tutorial-ingress-gateway-canary"               # Set reference
spec:
  gatewayClassName: tigera-gateway-class       # Set name of GatewayClass object
  listeners:
  - name: tcp-3306-allow-tcproute
    protocol: TCP
    port: 3306
    allowedRoutes:
      kinds:
      - kind: TCPRoute
---
# Purpose : Form Kubernetes TCPRoute Object
# Required Kubernetes API Resource
#   NAME        SHORTNAMES  APIVERSION                           NAMESPACED   KIND
#   tcproutes               gateway.networking.k8s.io/v1alpha2   true         TCPRoute
#
apiVersion: gateway.networking.k8s.io/v1alpha2     # Set API resource
kind: TCPRoute                                     # Set object kind
metadata:
  name: listen-tcp-3306-allow-tcproute-mysql-3306  # Set object name
  namespace: mysql                                 # Object is in effect in Namespace "mysql"     
  annotations:
    creator/author: "Thomas Rausch, Atos"          # Set creator/author
    version: "2025-12-03"                          # Set version
    description: "Form TCPRoute object from Gateway 'listen-tcp-3306-allow-tcproute-mysql' to Service 'mysql' on TCP Port 3306"  # Set description
    reference: "https://docs.tigera.io/calico/latest/networking/ingress-gateway/tutorial-ingress-gateway-canary"           # Set reference
spec:
  parentRefs:
  - name: listen-tcp-3306-allow-tcproute-mysql   # Set parent Gateway object
  rules:
  - backendRefs:
    - name: mysql-clusterip                      # Set backend Service
      port: 3306                                 # Set backend TCP port
---
# Purpose : Form Kubernetes ReferenceGrant Object
# Required Kubernetes API Resource
#   NAME              SHORTNAMES  APIVERSION                           NAMESPACED   KIND
#   referencegrants   refgrant     ateway.networking.k8s.io/v1beta1    true         ReferenceGrant
#
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: tcproute-default-to-mysql
  namespace: mysql
  annotations:
    creator/author: "Thomas Rausch, Atos"          # Set creator/author
    version: "2025-12-03"                          # Set version
    description: "Allows TCPRoute from Gateway to Service in Namespace 'mysql'"                                      # Set description
    reference: "https://docs.tigera.io/calico/latest/networking/ingress-gateway/tutorial-ingress-gateway-canary"     # Set reference
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: TCPRoute
    namespace: default
  to:
  - group: ""
    kind: Service
---
# PreRequisite - GatewayClass ""
#   NAME             SHORTNAMES   APIVERSION                     NAMESPACED   KIND
#   gatewayclasses   gc           gateway.networking.k8s.io/v1   false        GatewayClass
#
#
#   apiVersion: gateway.networking.k8s.io/v1
#   kind: GatewayClass
#   metadata:
#     name: tigera-gateway-class
#   spec:
#     controllerName: gateway.envoyproxy.io/gatewayclass-controller
#     parametersRef:
#       group: gateway.envoyproxy.io
#       kind: EnvoyProxy
#       name: envoy-proxy-config
#       namespace: tigera-gateway
