# Purpose : Form Kubernetes PersistentVolume Object
# Required Kubernetes API Resource
#   NAME                SHORTNAMES  APIVERSION   NAMESPACED   KIND
#   persistentvolumes   pv          v1           false        PersistentVolume
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    app: mysql
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mysql
  claimRef:
    name: mysql-pv-claim
    namespace: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: mysql
  labels:
    app: mysql
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
