apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mysql-tcp-gateway
spec:
  gatewayClassName: mysql-tcp-gateway-class
  listeners:
  - name: mysql-tcp-3306
    protocol: TCP
    port: 3306
    allowedRoutes:
      kinds:
      - kind: TCPRoute
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: mysql-tcp-route
spec:
  parentRefs:
  - name: mysql-tcp-gateway
    sectionName: mysql-tcp-3306
  rules:
  - backendRefs:
    - name: mysql-tcp-3306
      port: 3306
