apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngrok-ingress
  namespace: default
spec:
  ingressClassName: ngrok
  rules:
    - http:
        paths:
          - path: /foo
            pathType: Prefix
            backend:
              service:
                name: foo-service
                port:
                  number: 8080
          - path: /bar
            pathType: Prefix
            backend:
              service:
                name: bar-service
                port:
                  number: 8080
